# Master Task for installing and configuring MariaDB, Apache & WORDPRESS
- name: enabling the PHP 7.3 Remi repository
  command: yum-config-manager --enable remi-php73 -y
  tags: php
- name: Installing PHP and other pkgs
  yum: pkg={{ item }}  state=present
  with_items:
   - php
   - php-common
   - php-mysql
   - php-gd
   - php-xml
   - php-mbstring
     #   - php-mcrypt
   - php-xmlrpc
   - unzip
   - wget
   - firewalld
  tags: php
- name: Installing and Configuring MariaDB and MariaDB-CLient For WordBress
  include_tasks: database.yml
  tags: database
- name : Installing and configuring httpd server for WordBress
  include_tasks: webserver.yml
  tags: webserver
  
- name: Downloading and configuring WORDPRESS 
  include_tasks: wordpress.yml
  tags: wordpress
