- name: Install apache web server
  yum: pkg=httpd state=present
  tags: webserver
- name: Start and enable httpd
  service: name=httpd state=restarted enabled=yes
  tags: webserver
- name: Enable http service on the remote host
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
  tags: webserver
- name: Reload firewalld service after enabling http service
  service: name=firewalld state=restarted enabled=yes

